from django.urls import path
from .views import home, profile, RegisterView, showMessage, registerPage, homePage, usersCards, \
usersAccount, modify, userPointTransactions, firstYear, menu, tableReservation, pickup, wantLessons, \
    calendar, update_points, redirect_view, regieMarketplace, giveLessons, homePage, withPoints, withoutPoints, \
    collegeFee

urlpatterns = [
    path('pages-login.html', home, name='users-home'),
    path('pages-register.html', registerPage, name='pages-register'),
    path('index.html', homePage, name='home-page'),
    path('users-cards.html', usersCards, name='users-cards'),
    path('users-account.html', usersAccount, name='users-account'),
    path('pages-register.html', modify, name='modify'),
    path('user-point-transactions.html', userPointTransactions),
    path('first-year.html', firstYear),
    path('want-lessons.html', wantLessons),
    path('table-reservation.html', tableReservation),
    path('pickup.html', pickup),
    path('calendar.html', calendar),
    path('user-point-transactions.html', userPointTransactions),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('profile/', profile, name='users-profile'),
    path('regie-marketplace.html', regieMarketplace),
    path('give-lessons.html', giveLessons),
    path('home.html', homePage),
    path('menu.html', menu),
    path('with-points.html', withPoints),
    path('without-points.html', withoutPoints),
    path('college-fee.html', collegeFee),
    path('updaterecords/', update_points),
    path('updaterecords/users-account.html', usersAccount, name='users-account'),
    path('updaterecords/pages-login.html', home, name='users-home'),
    path('updaterecords/pages-register.html', registerPage, name='pages-register'),
    path('updaterecords/index.html', homePage, name='home-page'),
    path('updaterecords/users-cards.html', usersCards, name='users-cards'),
    path('updaterecords/pages-register.html', modify, name='modify'),
    path('updaterecords/user-point-transactions.html', userPointTransactions),
    path('updaterecords/first-year.html', firstYear),
    path('updaterecords/want-lessons.html', wantLessons),
    path('updaterecords/table-reservation.html', tableReservation),
    path('updaterecords/pickup.html', pickup),
    path('updaterecords/calendar.html', calendar),
    path('updaterecords/user-point-transactions.html', userPointTransactions),
    path('updaterecords/register/', RegisterView.as_view(), name='users-register'),
    path('updaterecords/profile/', profile, name='users-profile'),
    path('updaterecords/give-lessons.html', giveLessons),
    path('updaterecords/menu.html', menu),
    path('updaterecords/home.html', homePage),
    path('updaterecords/with-points.html', withPoints),
    path('updaterecords/without-points.html', withoutPoints),
    path('updaterecords/regie-marketplace.html', regieMarketplace),
    path('updaterecords/college-fee.html', collegeFee),
]
